module.exports = {
	// AUTHENTICATION
	AUTHENTICATING: 'AUTHENTICATING',
	AUTHENTICATION_SUCCESS: 'AUTHENTICATION_SUCCESS',
	AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
	LOGOFF: 'LOGOFF',
	SESSION_STALE: 'SESSION_STALE',
	//MEMBER SEARCH
	MEMBER_SEARCHING: 'MEMBER_SEARCHING',
	MEMBER_SEARCH: 'MEMBER_SEARCH',
	MEMBER_SEARCH_ERROR: 'MEMBER_SEARCH_ERROR',
	MEMBER_OPPORTUNITIES: 'MEMBER_OPPORTUNITIES',
	MEMBER_OPPORTUNITIES_ERROR: 'MEMBER_OPPORTUNITIES_ERROR',
	MEMBER_ACTIVITY: 'MEMBER_ACTIVITY',
	MEMBER_ACTIVITY_ERROR: 'MEMBER_ACTIVITY_ERROR',
	MEMBER_OPPORTUNITY: 'MEMBER_OPPORTUNITY',
	MEMBER_OPPORTUNITY_ERROR: 'MEMBER_OPPORTUNITY_ERROR'
};